version: 2.0

jobs:
  test:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    branches:
      ignore:
        - master

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest -v tests

  publish:
    docker:
    - image: circleci/python:3.6

    working_directory: ~/repo

    branches:
      only:
      - master

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt

      - save_cache:
         paths:
           - ./venv
         key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest -v tests

      - run:
          name: build packages
          command: |
            . venv/bin/activate
            python setup.py sdist bdist_wheel

      - run:
          name: publish on pypi
          command: |
            . venv/bin/activate
            twine upload dist/* -u $USER -p $PASSWORD
